# Generated by Django 2.2.7 on 2019-11-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='keterangan',
            field=models.CharField(choices=[('KK', 'Keterangan Kuliah'), ('CK', 'Cuti Kuliah')], max_length=2),
        ),
    ]
