# Generated by Django 2.2.7 on 2019-12-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuti', '0003_auto_20191129_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='keperluan',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='keterangan',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='jenis_surat',
            field=models.CharField(choices=[('KK', 'Keterangan Kuliah'), ('CK', 'Cuti Kuliah')], max_length=2),
        ),
    ]
