# Generated by Django 2.2.7 on 2019-12-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuti', '0006_auto_20191206_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tgl_surat',
            field=models.DateField(auto_now=True),
        ),
    ]
