# Generated by Django 2.2.7 on 2019-11-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191116_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='jurusan',
            field=models.TextField(choices=[('IF', 'INFORMATIKA'), ('SI', 'SISTEM INFORMASI')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tahun_masuk',
            field=models.TextField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
