# Generated by Django 2.2.7 on 2019-12-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191116_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tanggal_lahir',
            field=models.DateField(null=True),
        ),
    ]
